name: Build and Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: d4c4n/emil-emoji:latest
        platforms: linux/arm/v7,linux/arm64

    # Install Tailscale on the GitHub runner
    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}

    # Deploy to Raspberry Pi via Tailscale IP
    - name: Deploy to Raspberry Pi
      run: |
        ssh -o StrictHostKeyChecking=no pi@100.81.225.114 "
        docker pull d4c4n/emil-emoji:latest &&
        docker stop emil-emoji || true &&
        docker rm emil-emoji || true &&
        docker run -d --name emil-emoji -p 3000:3000 d4c4n/emil-emoji:latest
        "
